# Generated by Django 4.1.7 on 2023-03-05 20:30

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    User = apps.get_model('core.CustomUser')
    serj = User(
        username='serj',
        email='serj@example.com',
        password=make_password('111'),
        is_staff=True,
        is_superuser=True,
    )
    serj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
